# Generated by Django 6.0 on 2025-12-16 22:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "ordering": ["country"],
            },
        ),
        migrations.CreateModel(
            name="Career",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(upload_to="career/")),
                ("department", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("employment_type", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("responsibilities", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                ("application_email", models.EmailField(blank=True, max_length=254)),
                ("apply_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Career",
                "verbose_name_plural": "Careers",
                "ordering": ["priority", "-posted_at"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuing_authority", models.CharField(max_length=255)),
                ("certificate_number", models.CharField(max_length=255)),
                ("issue_date", models.DateField(blank=True)),
                (
                    "certificate_image",
                    models.ImageField(blank=True, upload_to="certificates/"),
                ),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Certifications",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("establishment_year", models.IntegerField(default=2023)),
                ("license_number", models.CharField(max_length=255)),
                ("total_deployment", models.IntegerField(default=2500)),
                ("experience_years", models.IntegerField(default=2)),
                ("client_satisfaction", models.IntegerField(default=100)),
                ("mission", models.TextField()),
                ("vision", models.TextField()),
                ("values", models.TextField()),
                ("about_text", models.TextField()),
                ("about_image", models.ImageField(upload_to="company/")),
                ("logo", models.ImageField(upload_to="company/logo/")),
                (
                    "mission_image",
                    models.ImageField(blank=True, upload_to="company/mission/"),
                ),
                (
                    "vision_image",
                    models.ImageField(blank=True, upload_to="company/vision/"),
                ),
                (
                    "values_image",
                    models.ImageField(blank=True, upload_to="company/values"),
                ),
                (
                    "about_background_image",
                    models.ImageField(blank=True, upload_to="company/bg_image"),
                ),
                ("hero_image", models.ImageField(blank=True, upload_to="hero/")),
                ("hero_image1", models.ImageField(blank=True, upload_to="hero/")),
                ("hero_image2", models.ImageField(blank=True, upload_to="hero/")),
                ("hero_image3", models.ImageField(blank=True, upload_to="hero/")),
                (
                    "hero_headline",
                    models.CharField(
                        default="Trusted International Recruitment Partner Since 2023",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company Info",
                "verbose_name_plural": "Company Infos",
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("company", models.CharField(blank=True, max_length=200)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("general", "General Inquiry"),
                            ("employer", "Employer/Recruitment"),
                            ("job_seeker", "Job Application"),
                            ("training", "Training Inquiry"),
                            ("complaint", "Complaint"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSRProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("impact_statement", models.TextField()),
                ("featured_image", models.ImageField(upload_to="csr/")),
                ("date", models.DateField()),
                ("location", models.CharField(max_length=200)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "CSR Project",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("employer_form", "Employer Form"),
                            ("candidate_form", "Candidate Form"),
                            ("demand_letter", "Demand Letter Template"),
                            ("power_of_attorney", "Power of Attorney"),
                            ("medical_checklist", "Medical Checklist"),
                            ("policy", "Policy Document"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("file", models.FileField(upload_to="documents/")),
                ("file_size", models.CharField(blank=True, max_length=50)),
                ("download_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="FAQCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "FAQ Category",
                "verbose_name_plural": "FAQ Categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "icon",
                    models.CharField(
                        help_text="CSS icon class or emoji", max_length=50
                    ),
                ),
                ("description", models.TextField()),
                ("overview", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="industries/")),
                ("display_order", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="JapanLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intro_title", models.CharField(max_length=200)),
                ("intro_description", models.TextField()),
                ("commitment_title", models.CharField(max_length=200)),
                ("commitment_intro", models.TextField(blank=True)),
                ("preparation_title", models.CharField(max_length=200)),
                ("preparation_intro", models.TextField(blank=True)),
                ("trust_title", models.CharField(max_length=200)),
                ("trust_intro", models.TextField(blank=True)),
                ("vision_title", models.CharField(max_length=200)),
                ("vision_intro", models.TextField(blank=True)),
                (
                    "commitment_image",
                    models.ImageField(blank=True, upload_to="japan/sections/"),
                ),
                (
                    "preparation_image",
                    models.ImageField(blank=True, upload_to="japan/sections/"),
                ),
                (
                    "trust_image",
                    models.ImageField(blank=True, upload_to="japan/sections/"),
                ),
                (
                    "vision_image",
                    models.ImageField(blank=True, upload_to="japan/sections/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Japan Landing Page",
                "verbose_name_plural": "Japan Landing Pages",
            },
        ),
        migrations.CreateModel(
            name="JapanProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Secondary title or short description",
                        max_length=255,
                    ),
                ),
                (
                    "overview",
                    models.TextField(help_text="Program overview and description"),
                ),
                (
                    "language_training_title",
                    models.CharField(
                        default="Japanese Language Training", max_length=255
                    ),
                ),
                (
                    "training_duration",
                    models.CharField(
                        blank=True,
                        help_text="Required for SSW; optional for Engineer/Specialist",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        help_text="JLPT/JFT or professional communication level",
                        max_length=150,
                    ),
                ),
                ("objective", models.TextField(help_text="Objective of the training")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="japan_programs/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Japan Training Program",
                "verbose_name_plural": "Japan Training Programs",
                "ordering": ["program_type", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JapanProgramType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Japan Program Type",
                "verbose_name_plural": "Japan Program Types",
            },
        ),
        migrations.CreateModel(
            name="Leadership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(blank=True, upload_to="leadership/")),
                ("email", models.URLField(blank=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Leadership",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="MediaAlbum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "album_type",
                    models.CharField(
                        choices=[
                            ("office", "Office"),
                            ("training", "Training"),
                            ("interviews", "Interviews"),
                            ("orientation", "Orientation"),
                            ("client_visits", "Client Visits"),
                            ("events", "Events"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("cover_image", models.ImageField(upload_to="gallery/covers/")),
                ("date", models.DateField()),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PrivacyPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Privacy Policy", max_length=200)),
                ("slug", models.SlugField(default="privacy-policy", unique=True)),
                ("content", models.TextField()),
                ("last_updated", models.DateField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Privacy Policy",
                "verbose_name_plural": "Privacy Policies",
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Terms of Service", max_length=200)),
                ("slug", models.SlugField(default="terms-of-service", unique=True)),
                ("content", models.TextField()),
                ("last_updated", models.DateField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Terms of Service",
                "verbose_name_plural": "Terms of Service",
            },
        ),
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("language", "Language"),
                            ("vocational", "Vocational"),
                            ("technical", "Technical"),
                            ("soft_skills", "Soft Skills"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("duration", models.CharField(max_length=100)),
                (
                    "course_image",
                    models.ImageField(blank=True, upload_to="training/courses/"),
                ),
                ("syllabus", models.TextField(blank=True)),
                ("prerequisites", models.TextField(blank=True)),
                ("certification_provided", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Training Courses",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingFacility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("capacity", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, upload_to="training/facilities/"),
                ),
                ("display_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Training Facilities",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=300)),
                ("answer", models.TextField()),
                ("display_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs",
                        to="app.faqcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="EmployerInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_person", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                (
                    "required_positions",
                    models.TextField(help_text="List of positions needed"),
                ),
                ("number_of_workers", models.IntegerField()),
                ("job_description", models.TextField(blank=True)),
                ("expected_start_date", models.DateField(blank=True, null=True)),
                ("contract_duration", models.CharField(blank=True, max_length=100)),
                (
                    "demand_letter",
                    models.FileField(blank=True, upload_to="employer/demand_letters/"),
                ),
                (
                    "additional_documents",
                    models.FileField(blank=True, upload_to="employer/documents/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("processing", "Processing"),
                            ("quotation_sent", "Quotation Sent"),
                            ("approved", "Approved"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inquiries",
                        to="app.industry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Employer Inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("logo", models.ImageField(blank=True, upload_to="clients/")),
                ("website", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "industry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="clients",
                        to="app.industry",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="JapanBulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("commitment", "Commitment"),
                            ("preparation", "Preparation System"),
                            ("trust", "Why Japan Trusts KHRM"),
                            ("vision", "Vision"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="app.japanlandingpage",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "order"],
            },
        ),
        migrations.CreateModel(
            name="JapanProgramTrainingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.CharField(help_text="Single training point", max_length=255),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_points",
                        to="app.japanprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Point",
                "verbose_name_plural": "Training Points",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="japanprogram",
            name="program_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="app.japanprogramtype",
            ),
        ),
        migrations.CreateModel(
            name="JapanTeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("photo", models.ImageField(blank=True, upload_to="japan/team/")),
                ("order", models.IntegerField(default=0)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members",
                        to="app.japanlandingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Japan Team Member",
                "verbose_name_plural": "Japan Team Members",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="jobs/")),
                ("country", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("requirements", models.TextField()),
                ("responsibilities", models.TextField(blank=True)),
                ("salary_range", models.CharField(blank=True, max_length=255)),
                ("contract_duration", models.CharField(blank=True, max_length=255)),
                ("vacancies", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("filled", "Filled"),
                            ("on_hold", "ON Hold"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="app.client",
                    ),
                ),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="app.industry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=255)),
                ("current_location", models.CharField(max_length=255)),
                (
                    "resume",
                    models.FileField(
                        upload_to="applications/resumes/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "passport_copy",
                    models.ImageField(blank=True, upload_to="applications/passports/"),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, upload_to="applications/photos/"),
                ),
                ("years_of_experience", models.IntegerField(default=0)),
                ("previous_experience", models.TextField(blank=True)),
                ("skills", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Submitted"),
                            ("screening", "Screening"),
                            ("interview", "Interview Scheduled"),
                            ("medical", "Medical Process"),
                            ("selected", "Selected"),
                            ("rejected", "Rejected"),
                            ("deployed", "Deployed"),
                        ],
                        default="submitted",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="app.job",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "skill_level",
                    models.CharField(
                        choices=[
                            ("skilled", "Skilled"),
                            ("semi_skilled", "Semi-Skilled"),
                            ("professinal", "Professional"),
                            ("unskilled", "Unskilled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "industry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_categories",
                        to="app.industry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Job Categories",
                "ordering": ["industry", "name"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="app.jobcategory",
            ),
        ),
        migrations.CreateModel(
            name="MediaPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/photos/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("display_order", models.IntegerField(default=0)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photo",
                        to="app.mediaalbum",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="NewsPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("news", "News"),
                            ("deployment", "Deployment"),
                            ("event", "Event"),
                            ("announcement", "Announcement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("featured_image", models.ImageField(upload_to="news/")),
                ("summary", models.TextField(max_length=300)),
                ("content", models.TextField()),
                ("is_published", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.CharField(max_length=50)),
                ("facebook", models.URLField()),
                (
                    "latitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                (
                    "longitude",
                    models.DecimalField(blank=True, decimal_places=6, max_digits=9),
                ),
                ("is_headquarter", models.BooleanField(default=False)),
                (
                    "office_image",
                    models.ImageField(blank=True, upload_to="company/office"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offices",
                        to="app.branch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Offices",
                "ordering": ["display_order", "branch__country"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_name", models.CharField(max_length=200)),
                ("person_position", models.CharField(max_length=200)),
                (
                    "person_photo",
                    models.ImageField(blank=True, upload_to="testimonials/"),
                ),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("testimonial_text", models.TextField()),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="app.client",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WhyChooseJapanProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_choose", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_choose_points",
                        to="app.japanprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Why Choose Japan Program",
                "verbose_name_plural": "Why Choose Japan Programs",
                "ordering": ["order"],
            },
        ),
    ]
