# Generated by Django 5.2.8 on 2025-12-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image1',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image2',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='hero_image3',
            field=models.ImageField(blank=True, upload_to='hero/'),
        ),
    ]
