# Generated by Django 6.0 on 2025-12-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="category",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("job_seekers", "Job Seekers"),
                    ("employers", "Employers"),
                    ("training", "Training"),
                    ("visa", "Visa & Documentation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterModelOptions(
            name="faq",
            options={
                "ordering": ["category", "display_order"],
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
            },
        ),
        migrations.DeleteModel(
            name="FAQCategory",
        ),
    ]
