# Generated by Django 6.0 on 2025-12-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_faq_category_alter_faq_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="csrproject",
            name="featured_image",
            field=models.ImageField(blank=True, upload_to="csr/"),
        ),
    ]
