# Generated by Django 6.0 on 2025-12-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_companyinfo_hero_image1_companyinfo_hero_image2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JAPANProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("SSW", "Specified Skilled Worker (SSW)"),
                            (
                                "ENGINEER",
                                "Engineer / Specialist in Humanities / International Services",
                            ),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Main program title", max_length=255),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True,
                        help_text="Secondary title or short description",
                        max_length=255,
                    ),
                ),
                (
                    "overview",
                    models.TextField(help_text="Program overview and description"),
                ),
                (
                    "language_training_title",
                    models.CharField(
                        default="Japanese Language Training", max_length=255
                    ),
                ),
                (
                    "training_duration",
                    models.CharField(
                        blank=True,
                        help_text="Required for SSW; optional for Engineer/Specialist",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        help_text="JLPT/JFT or professional communication level",
                        max_length=150,
                    ),
                ),
                (
                    "training_content",
                    models.TextField(help_text="Training content (use bullet points)"),
                ),
                ("objective", models.TextField(help_text="Objective of the training")),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="japan_programs/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Japan Training Program",
                "verbose_name_plural": "Japan Training Programs",
                "ordering": ["program_type", "-created_at"],
            },
        ),
    ]
