# Generated by Django 6.0 on 2025-12-15 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_japanprogram"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="japanprogram",
            name="training_content",
        ),
        migrations.CreateModel(
            name="JAPANProgramTrainingPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "point",
                    models.CharField(help_text="Single training point", max_length=255),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_points",
                        to="app.japanprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Point",
                "verbose_name_plural": "Training Points",
                "ordering": ["order"],
            },
        ),
    ]
