# Generated by Django 6.0 on 2025-12-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_japanprogram_training_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="japanprogram",
            name="title",
        ),
        migrations.AlterField(
            model_name="japanprogram",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("SSW", "Specified Skilled Worker (SSW) Program"),
                    (
                        "ENGINEER",
                        "Engineer / Specialist in Humanities / International Services",
                    ),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
