# Generated by Django 5.2.8 on 2025-11-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_seed_career_csr_japan'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='about_background_image',
            field=models.ImageField(blank=True, upload_to='company/sections/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/logo/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='mission_image',
            field=models.ImageField(blank=True, upload_to='company/sections/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='values_image',
            field=models.ImageField(blank=True, upload_to='company/sections/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='vision_image',
            field=models.ImageField(blank=True, upload_to='company/sections/'),
        ),
        migrations.AddField(
            model_name='japanlandingpage',
            name='commitment_image',
            field=models.ImageField(blank=True, upload_to='japan/sections/'),
        ),
        migrations.AddField(
            model_name='japanlandingpage',
            name='preparation_image',
            field=models.ImageField(blank=True, upload_to='japan/sections/'),
        ),
        migrations.AddField(
            model_name='japanlandingpage',
            name='trust_image',
            field=models.ImageField(blank=True, upload_to='japan/sections/'),
        ),
        migrations.AddField(
            model_name='japanlandingpage',
            name='vision_image',
            field=models.ImageField(blank=True, upload_to='japan/sections/'),
        ),
    ]
