# Generated by Django 6.0 on 2025-12-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_japanprogram_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhyChooseJapanProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("why_choose", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="why_choose_points",
                        to="app.japanprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Why Choose Japan Program",
                "verbose_name_plural": "Why Choose Japan Programs",
                "ordering": ["order"],
            },
        ),
    ]
