# Generated by Django 6.0 on 2025-12-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_whychoosejapanprogram"),
    ]

    operations = [
        migrations.AddField(
            model_name="career",
            name="image",
            field=models.ImageField(default="", upload_to="career"),
            preserve_default=False,
        ),
    ]
