# Generated by Django 6.0 on 2025-12-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_career_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(blank=True, upload_to="jobs/"),
        ),
    ]
