# Generated by Django 6.0 on 2025-12-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="office",
            name="facebook",
            field=models.URLField(default="https://www.facebook.com/khrmnepal"),
            preserve_default=False,
        ),
    ]
